version: "3"
services:
  jenkins:
    container_name: jenkins_cli
    image: "bosen:jenkins_docker"
    build:
      context: ./
      dockerfile: DockerFile
    volumes: 
      - jenkins-data:/var/jenkins_home
      #- /var/run/docker.sock:/var/run/docker.sock
      - ./home:/home
    ports:
      - 8080:8080

volumes:
  jenkins-data:

