#!/usr/bin/env groovy

pipeline {
    agent any 
    stages {
        stage('Check Repo Exist State') {
            steps {
                echo 'Check Repo'
                ls
            }
        }
        stage('Install Dependencies') {
            steps {
                echo 'Installing Dependencies'
                npm install
            }
        }
        stage('Run Tests') {
            steps {
                echo 'Running Test'
                npm test
            }
        }
    }
}