#!/usr/bin/env groovy

pipeline {
    agent any 
    stages {
        stage('Check Repo Exist State') {
            steps {
                echo 'Check Repo'
                sh 'ls && pwd'
            }
        }

        stage('Clean Up') {
            steps {
                echo 'Cleaning Up'
                sh 'rm -r *'
            }
        }

        stage('Check Repo Exist State 2') {
            steps {
                echo 'Check Repo 2'
                sh 'ls && pwd'
            }
        }
        // stage('Install Dependencies') {
        //     steps {
        //         echo 'Installing Dependencies'
        //         sh 'npm install'
        //     }
        // }
        // stage('Run Tests') {
        //     steps {
        //         echo 'Running Test'
        //         sh './jenkins/scripts/test.sh'
        //     }
        // }
    }
}